### ISSUE TITLE
Dock button disappeared

### ISSUE THREAD

**Issue by LeonardoGentile** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#126] opened 2015-04-20 14:37 UTC
Hello,
I'm on Canary 44.0.2375.0 canary (64-bit) for Mac.
Since the last update the button to dock/undock the developer tools has disappeared.
First I though that this was a chrome bug but then I deactivated your extension and it appeared again.

May I help you in any way to solve the problem?

![image](https://cloud.githubusercontent.com/assets/412061/7232355/64bc3b6e-e77b-11e4-82dd-de1d6d21fd48.png)

![image](https://cloud.githubusercontent.com/assets/412061/7232366/6f3cf90c-e77b-11e4-858c-dcd68b33f271.png)

**Comment by mauricecruz** [comment] 2015-04-20 14:58
More than likely caused by selector syntax change and some css updates to devtools. I push all my updates to https://github.com/mauricecruz/zero-base-themes. If you want to take a stab and fixing it, feel free to fork it.

I'll try to get to it in a day or two. Day job is kicking my ass right now.

**Comment by mauricecruz** [comment] 2015-04-25 01:36
@LeonardoGentile fixed in 1.7.8. Please confirm.

**Comment by ramgp** [comment] 2015-04-25 05:38
@mauricecruz Fix is confirmed, thank you rock!

**Comment by mauricecruz** [comment] 2015-04-25 19:11
@ramp :+1:

**Closed by mauricecruz** 2015-04-25 19:11 UTC

**Comment by dima-f1** [comment] 2015-05-21 16:10
Today noticed:
Chrome 43.0.2357.65m Win7
![mauricecruz_zero-base-themes - google chrome 2015-05-21 19 05 43](https://cloud.githubusercontent.com/assets/5352626/7753222/ae77a9c6-ffec-11e4-8046-86d85afa4355.png)

**Comment by LeonardoGentile** [comment] 2015-05-30 23:45
Kind of late but I confirm on 45.0.2417.0 Mac
Thank you so much! :+1:
